version: '3.7'
services:
  awin-user-tracking:
    build:
      context: ./awin-user-tracking
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "9890:9890"
    container_name: awin-user-tracking
    networks:
      - default
    depends_on:
      - "mongodb"
      - "mongodb-management"
  mongodb:
    image: mongo:7.0
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - db-data:/data/db
    networks:
      - default
  mongodb-management:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017/
    networks:
      - default
networks:
  default:
    name: test
    external: true
volumes:
  db-data: